import Phaser from 'phaser';
import {DIFFICULTIES,ENEMIES,EnemyKey,STAGES,UPGRADES} from './data';
import type {FilthyAudio} from './audio';

type Foe=Phaser.Physics.Arcade.Sprite&{kind:EnemyKey;hp:number;maxHp:number;damage:number;worth:number;speed:number;style:string;engage:number;nextAttack:number;specialAt:number;boss:boolean;dead:boolean;shadow?:Phaser.GameObjects.Ellipse;barBg?:Phaser.GameObjects.Rectangle;bar?:Phaser.GameObjects.Rectangle};
type Loot=Phaser.Physics.Arcade.Sprite&{loot:string};
type Shot=Phaser.Physics.Arcade.Sprite&{damage?:number};
type DifficultyKey=keyof typeof DIFFICULTIES;
type RunState={stage:number;wave:number;hp:number;maxHp:number;high:number;packets:number;cash:number;score:number;combo:number;kills:number;damageTaken:number;startedAt:number;upgrades:Set<string>;weapon:string;weaponHits:number};

export class GameScene extends Phaser.Scene{
 audio:FilthyAudio;auto=false;difficultyKey:DifficultyKey='cooked';player!:Phaser.Physics.Arcade.Sprite;playerShadow!:Phaser.GameObjects.Ellipse;highAura!:Phaser.GameObjects.Ellipse;ground!:Phaser.GameObjects.Rectangle;foes!:Phaser.Physics.Arcade.Group;loot!:Phaser.Physics.Arcade.Group;shots!:Phaser.Physics.Arcade.Group;background!:Phaser.GameObjects.Image;ambient!:Phaser.GameObjects.Rectangle;weaponView?:Phaser.GameObjects.Image;
 cursors!:Phaser.Types.Input.Keyboard.CursorKeys;keys!:Record<string,Phaser.Input.Keyboard.Key>;touch:Record<string,boolean>={};state!:RunState;ready=false;running=false;paused=false;invulnerable=false;attacking=false;transition=false;spawning=false;nextPlayerHit=0;nextHudAt=0;stunnedUntil=0;lastAttack=0;comboTimer=0;damageBuff=1;packetTimer?:Phaser.Time.TimerEvent;hazardTimer?:Phaser.Time.TimerEvent;activeBoss?:Foe;
 constructor(audio:FilthyAudio){super('Game');this.audio=audio}
 init(data:{auto?:boolean}){this.auto=!!data?.auto;this.running=false}
 preload(){
  for(let r=0;r<4;r++)for(let i=1;i<=4;i++)this.load.image(`jack${r}-${i}`,`assets/characters/jack-row${r}/0${i}.png`);
  for(let r=0;r<8;r++)for(let i=1;i<=4;i++)this.load.image(`woman${r}-${i}`,`assets/characters/woman-row${r}/0${i}.png`);
  for(let r=0;r<4;r++)for(let i=1;i<=4;i++)this.load.image(`man${r}-${i}`,`assets/enemies/man-row${r}/0${i}.png`);
  for(let r=0;r<4;r++)for(let i=1;i<=4;i++)this.load.image(`prop${r}-${i}`,`assets/props/row${r}/0${i}.png`);
  this.load.image('bg-club','assets/backgrounds/pink-pigeon.webp');this.load.image('bg-alley','assets/backgrounds/alley.webp');this.load.image('bg-casino','assets/backgrounds/casino.webp');this.load.image('bg-kebab','assets/backgrounds/kebab.webp');
 }
 create(){
  this.createAnimations();this.physics.world.setBounds(0,0,1500,720);this.cameras.main.setBounds(0,0,1500,720);this.cameras.main.setBackgroundColor('#080508');
  this.background=this.add.image(640,360,'bg-club').setDisplaySize(1280,720).setScrollFactor(0).setDepth(-20);
  this.ambient=this.add.rectangle(640,360,1280,720,0xff1d9a,.07).setScrollFactor(0).setBlendMode(Phaser.BlendModes.ADD).setDepth(-15);this.tweens.add({targets:this.ambient,alpha:{from:.025,to:.11},duration:900,yoyo:true,repeat:-1});
  this.add.rectangle(750,690,1500,90,0x08040a,.63).setDepth(-2);this.add.rectangle(750,650,1500,4,0xff299d,.5).setDepth(-1);
  this.ground=this.add.rectangle(750,672,1500,44,0,0);this.physics.add.existing(this.ground,true);
  this.foes=this.physics.add.group();this.loot=this.physics.add.group();this.shots=this.physics.add.group({allowGravity:false});
  this.player=this.physics.add.sprite(220,548,'jack0-1').setScale(.8).setCollideWorldBounds(true).setDepth(5).setActive(false).setVisible(false);this.setBody(this.player);this.player.play('jack-idle');
  this.playerShadow=this.add.ellipse(this.player.x,647,112,22,0x000000,.45).setDepth(2).setVisible(false);this.highAura=this.add.ellipse(this.player.x,this.player.y,118,210,0x19ead8,0).setBlendMode(Phaser.BlendModes.ADD).setDepth(3).setVisible(false);
  this.physics.add.collider(this.player,this.ground);this.physics.add.collider(this.foes,this.ground);this.physics.add.collider(this.loot,this.ground);this.physics.add.collider(this.shots,this.ground,s=>(s as Phaser.GameObjects.GameObject).destroy());this.physics.add.overlap(this.player,this.foes,(_,f)=>this.enemyContact(f as Foe));this.physics.add.overlap(this.player,this.loot,(_,l)=>this.collect(l as Loot));this.physics.add.overlap(this.player,this.shots,(_,s)=>this.projectileHit(s as Shot));
  this.cameras.main.startFollow(this.player,true,.09,.09);this.cameras.main.setDeadzone(280,100);
  this.cursors=this.input.keyboard!.createCursorKeys();this.keys=this.input.keyboard!.addKeys('W,A,S,D,J,H,K,L,T,SHIFT,ESC') as Record<string,Phaser.Input.Keyboard.Key>;
  const touch=(action:string,down:boolean)=>{this.touch[action]=down;if(down)this.action(action)},autopause=()=>{if(!this.paused&&!this.transition&&this.player.active)this.togglePause()};this.game.events.on('touch',touch);this.game.events.on('autopause',autopause);this.events.once('shutdown',()=>{this.game.events.off('touch',touch);this.game.events.off('autopause',autopause)});
  this.resetState();this.ready=true;if(this.auto)this.time.delayedCall(150,()=>this.startRun());
 }
 setDifficulty(key:string){if(key in DIFFICULTIES)this.difficultyKey=key as DifficultyKey}
 resetState(){this.state={stage:0,wave:0,hp:100,maxHp:100,high:0,packets:1,cash:0,score:0,combo:0,kills:0,damageTaken:0,startedAt:Date.now(),upgrades:new Set(),weapon:'',weaponHits:0}}
  startRun(){if(!this.ready){this.auto=true;return}if(this.running)return;this.running=true;this.clearWorld();this.state.stage=0;this.state.wave=0;this.state.hp=this.state.maxHp;this.state.startedAt=Date.now();this.player.setActive(true).setVisible(true).setPosition(220,548).clearTint();this.playerShadow.setVisible(true);this.highAura.setVisible(true);this.physics.resume();this.paused=false;this.loadStage()}
  loadStage(){const s=STAGES[this.state.stage],colours=[0xff1d9a,0x16d9ff,0xff9f12,0xffd88a];this.transition=true;this.hazardTimer?.remove(false);this.background.setTexture(s.background).setAlpha(0);this.ambient.setFillStyle(colours[this.state.stage],.07);this.tweens.add({targets:this.background,alpha:1,duration:650});this.player.setPosition(220,548).setVelocity(0);this.cameras.main.flash(350,255,30,150);this.audio.stage(this.state.stage);this.emitHud();this.toast(s.intro,2200);const d=DIFFICULTIES[this.difficultyKey];this.hazardTimer=this.time.addEvent({delay:Math.round((6500-this.state.stage*700)*d.hazard),loop:true,callback:()=>{if(!this.transition&&!this.paused)this.spawnHazard()}});this.time.delayedCall(1100,()=>{this.transition=false;this.startWave()})}
 startWave(){const s=STAGES[this.state.stage],list=s.waves[this.state.wave];this.spawning=true;this.emitHud();let at=0;const ev=this.time.addEvent({delay:520,repeat:list.length-1,callback:()=>{const slot=list[at++],kind=s.roster[slot];this.spawnFoe(kind,this.state.wave===s.waves.length-1);if(at===list.length)this.spawning=false}});if(!ev)this.spawning=false}
  spawnFoe(kind:EnemyKey,boss=false){const spec=ENEMIES[kind],diff=DIFFICULTIES[this.difficultyKey],row=Number(spec.sprite.replace(/\D/g,'')),prefix=spec.sprite.startsWith('woman')?'woman':'man',slot=this.foes.countActive(true);const x=Phaser.Math.Clamp(870+(slot%6)*105+Phaser.Math.Between(-24,24),850,1430);const scale=spec.scale*(boss?1.13:1),hp=Math.ceil(spec.hp*(boss?4:1)*diff.hp);const foe=this.foes.create(x,650-128*scale,`${prefix}${row}-1`) as Foe;Object.assign(foe,{kind,hp,maxHp:hp,damage:spec.damage*(boss?1.25:1)*diff.damage,worth:spec.worth*(boss?4:1)*diff.score,speed:spec.speed,style:spec.style,engage:64+(slot%4)*16,nextAttack:0,specialAt:this.time.now+3200,boss,dead:false});foe.setScale(scale).setDepth(4).setCollideWorldBounds(true).setFlipX(true);this.setBody(foe);foe.shadow=this.add.ellipse(foe.x,647,95*scale,18,0x000000,.38).setDepth(2);if(!boss){foe.barBg=this.add.rectangle(foe.x,foe.y-112*scale,54,7,0x140b15,.9).setStrokeStyle(1,0xffffff,.8).setDepth(8);foe.bar=this.add.rectangle(foe.x-25,foe.y-112*scale,50,3,0xff269c).setOrigin(0,.5).setDepth(9)}foe.play(`${prefix}${row}-walk`);if(boss){this.activeBoss=foe;const line=Phaser.Math.RND.pick(spec.lines);this.game.events.emit('bossIntro',{name:spec.name,line,image:`assets/${spec.sprite.startsWith('woman')?'characters':'enemies'}/${spec.sprite.startsWith('woman')?`woman-row${row}`:`man-row${row}`}/01.png`})}else if(Math.random()<.35)this.toast(Phaser.Math.RND.pick(spec.lines),850);this.emitHud()}
 update(time:number){
  if(!this.ready||!this.running)return;if(Phaser.Input.Keyboard.JustDown(this.keys.ESC)){this.togglePause();return}if(this.paused||this.transition||!this.player.active)return;
  const stunned=time<this.stunnedUntil,left=!stunned&&(this.cursors.left.isDown||this.keys.A.isDown||this.touch.left),right=!stunned&&(this.cursors.right.isDown||this.keys.D.isDown||this.touch.right);const body=this.player.body as Phaser.Physics.Arcade.Body;
  if(!this.attacking){this.player.setVelocityX(left?-275:right?275:body.blocked.down?0:this.player.body!.velocity.x*.96);if(left||right){this.player.setFlipX(left);if(body.blocked.down)this.player.play('jack-run',true)}else if(body.blocked.down)this.player.play('jack-idle',true)}
  if(!stunned&&(Phaser.Input.Keyboard.JustDown(this.cursors.space)||Phaser.Input.Keyboard.JustDown(this.keys.W))&&body.blocked.down)this.jump();
  if(!stunned){if(Phaser.Input.Keyboard.JustDown(this.keys.J))this.lightAttack();if(Phaser.Input.Keyboard.JustDown(this.keys.H))this.heavyAttack();if(Phaser.Input.Keyboard.JustDown(this.keys.SHIFT))this.dash();if(Phaser.Input.Keyboard.JustDown(this.keys.K))this.usePacket();if(Phaser.Input.Keyboard.JustDown(this.keys.L))this.pigeon();if(Phaser.Input.Keyboard.JustDown(this.keys.T))this.makeItRain()}
  this.updateFoes(time);if(!this.spawning&&!this.transition&&this.foes.countActive(true)===0)this.advanceWave();if(this.state.combo>0&&time>this.comboTimer){this.state.combo=0;this.emitHud()}if(this.weaponView){this.weaponView.setPosition(this.player.x+(this.player.flipX?-38:38),this.player.y+12).setFlipX(this.player.flipX)}
  const air=Math.max(0,630-this.player.y),charge=this.state.high/100;this.playerShadow.setPosition(this.player.x,647).setScale(Math.max(.45,1-air/260),1).setAlpha(Math.max(.15,.45-air/500));this.highAura.setPosition(this.player.x,this.player.y+15).setAlpha(charge>.35?.05+charge*.17:0).setScale(.82+Math.sin(time/120)*.05+charge*.18);
  if(time>=this.nextHudAt){this.nextHudAt=time+100;this.emitHud()}
 }
 action(a:string){if(a==='jump')this.jump();if(a==='hit')this.lightAttack();if(a==='heavy')this.heavyAttack();if(a==='dash')this.dash();if(a==='packet')this.usePacket();if(a==='pigeon')this.pigeon();if(a==='rain')this.makeItRain()}
 jump(){const b=this.player.body as Phaser.Physics.Arcade.Body;if(b.blocked.down)this.player.setVelocityY(-510)}
 lightAttack(){if(this.attacking||this.paused)return;const now=this.time.now;this.state.combo=now-this.lastAttack<480?Math.min(3,this.state.combo+1):1;this.lastAttack=now;this.comboTimer=now+1000;this.attacking=true;const frame=this.state.combo===1?1:this.state.combo===2?2:3;this.player.setTexture(`jack2-${frame}`);this.player.setVelocityX((this.player.flipX?-1:1)*(120+this.state.combo*30));this.time.delayedCall(85,()=>this.damageArc(105,1+(this.state.upgrades.has('double')?1:0)+(this.state.weapon?1:0),340));this.time.delayedCall(205,()=>{this.attacking=false;this.player.play('jack-idle')});this.audio.hit(false);if(this.state.weapon&&--this.state.weaponHits<=0)this.breakWeapon()}
 heavyAttack(){if(this.attacking||this.paused)return;const moneyShot=this.state.high>=95;if(moneyShot){this.state.high-=45;this.toast('MONEY SHOT — MAXIMUM DEGENERACY',900);this.unlock('money','MONEY SHOT');this.audio.special()}this.attacking=true;this.player.setTexture('jack2-3');this.player.setVelocityX(0);this.time.delayedCall(250,()=>{this.player.setTexture('jack2-4');this.damageArc(moneyShot?230:145,(this.state.upgrades.has('tradie')?6:3)+(this.state.weapon?2:0)+(moneyShot?4:0),moneyShot?820:620);this.cameras.main.shake(moneyShot?220:120,moneyShot?.02:.012);this.audio.hit(true);if(this.state.upgrades.has('filthy'))this.state.cash+=10});this.time.delayedCall(520,()=>{this.attacking=false;this.player.play('jack-idle')});if(this.state.weapon&&--this.state.weaponHits<=0)this.time.delayedCall(500,()=>this.breakWeapon())}
 damageArc(range:number,damage:number,knock:number){const dir=this.player.flipX?-1:1;let hits=0;this.foes.children.each(o=>{const f=o as Foe;if(f.active&&!f.dead&&Math.abs(f.y-this.player.y)<170){const dx=f.x-this.player.x;if(Math.sign(dx)===dir&&Math.abs(dx)<range){this.hitFoe(f,damage*this.damageBuff,dir*knock);hits++}}return true});if(hits){this.state.high=Math.min(100,this.state.high+5*hits);this.state.combo=Math.min(99,this.state.combo+hits);this.comboTimer=this.time.now+1100;if(this.state.combo>=10)this.unlock('combo','DOUBLE-DIGIT DEGENERATE')}}
 hitFoe(f:Foe,damage:number,knock:number){if(f.dead)return;f.hp-=damage;if(f.bar)f.bar.setScale(Math.max(0,f.hp/f.maxHp),1);f.setVelocity(knock,-145);f.setTintFill(0xffffff);this.time.delayedCall(70,()=>f.active&&f.clearTint());this.impact(f.x,f.y-60);if(f.boss)this.emitHud();if(f.hp<=0)this.defeat(f)}
 defeat(f:Foe){if(f.dead)return;f.dead=true;const spec=ENEMIES[f.kind],reward=Math.round(f.worth*(1+this.state.combo*.06));this.state.kills++;if(this.state.kills===1)this.unlock('first','CHERRY POPPED');if(spec.sprite.startsWith('woman'))this.unlockBaddie(f.kind);this.state.score+=reward;this.floatText(f.x,f.y-125,`+${reward}`,f.boss?'#ffd229':'#ffffff');this.state.cash+=this.state.upgrades.has('filthy')?20:10;this.state.high=Math.min(100,this.state.high+12);if(this.state.upgrades.has('shameless'))this.heal(3);this.blood(f.x,f.y);f.bar?.destroy();f.barBg?.destroy();f.shadow?.destroy();f.setTexture(`${spec.sprite}-4`);f.setVelocity((f.x<this.player.x?-1:1)*430,-330);f.setAngularVelocity(Phaser.Math.Between(-180,180));this.time.delayedCall(500,()=>{this.drop(f.x,f.y,f.boss);f.destroy()});if(f.boss){this.activeBoss=undefined;this.toast(`${spec.name}: ${Phaser.Math.RND.pick(spec.lines)}`,1000)}}
 updateFoes(time:number){this.foes.children.each(o=>{const f=o as Foe;if(!f.active||f.dead)return true;const dx=this.player.x-f.x,ad=Math.abs(dx),dir=Math.sign(dx)||1;f.shadow?.setPosition(f.x,647);f.barBg?.setPosition(f.x,f.y-112*f.scaleY);f.bar?.setPosition(f.x-25,f.y-112*f.scaleY);f.setFlipX(dir<0);if(f.boss&&time>f.specialAt){f.specialAt=time+Phaser.Math.Between(3800,5200);this.bossSpecial(f);return true}if(f.style==='tease'&&ad<260&&time>f.nextAttack){f.nextAttack=time+1750;this.seduce(f);return true}if(f.style==='ranged'&&ad<440){f.setVelocityX(0);if(time>f.nextAttack){f.nextAttack=time+1500;f.setTexture(`${ENEMIES[f.kind].sprite}-3`);this.shoot(f)}}else if(f.style==='heavy'&&ad<320&&time>f.nextAttack){f.nextAttack=time+1700;f.setTexture(`${ENEMIES[f.kind].sprite}-4`);this.time.delayedCall(340,()=>f.active&&f.setVelocityX(dir*480))}else if(ad>f.engage){f.setVelocityX(dir*f.speed*(f.boss?1.15:1));f.play(`${ENEMIES[f.kind].sprite}-walk`,true)}else{f.setVelocityX(0);if(time>f.nextAttack){f.nextAttack=time+(f.boss?650:950);f.setTexture(`${ENEMIES[f.kind].sprite}-${f.style==='tease'?3:4}`);this.time.delayedCall(170,()=>{if(f.active&&Math.abs(this.player.x-f.x)<115)this.hurt(f.damage,f.x)})}}return true})}
 seduce(f:Foe){f.setVelocityX(0).setTexture(`${ENEMIES[f.kind].sprite}-3`);const ring=this.add.image(f.x,f.y-60,'prop3-1').setTint(0xff4eb5).setScale(.15).setDepth(10);this.tweens.add({targets:ring,scale:1.1,alpha:0,duration:520,onComplete:()=>ring.destroy()});this.time.delayedCall(260,()=>{if(f.active&&Math.abs(this.player.x-f.x)<285){this.stunnedUntil=this.time.now+720;this.hurt(f.damage*.55,f.x);this.unlock('redflags','WEAK TO RED FLAGS');this.toast(`${ENEMIES[f.kind].name}: EYES UP, FUCKBOY`,700)}})}
 bossSpecial(f:Foe){if(!f.active||f.dead)return;const kind=f.kind;if(kind==='chad'){this.toast('CHAD CALLED IN VIP REINFORCEMENTS',900);if(this.foes.countActive(true)<4)this.spawnFoe(Phaser.Math.RND.pick(['roxi','lexi','lola'] as EnemyKey[]));return}if(kind==='goblin'){this.toast('THE GOBLIN STOLE YOUR FUCKING BAG',900);if(this.state.packets>0)this.state.packets--;const smoke=this.add.image(f.x,f.y-50,'prop3-4').setScale(.25).setDepth(12);f.setPosition(Phaser.Math.Between(700,1350),540);this.tweens.add({targets:smoke,scale:1,alpha:0,duration:450,onComplete:()=>smoke.destroy()});return}if(kind==='candy'){this.toast('CANDY IS FEEDING ON YOUR WALLET',900);const stolen=Math.min(35,this.state.cash);this.state.cash-=stolen;f.hp=Math.min(f.maxHp,f.hp+Math.max(2,stolen/8));this.emitHud();for(let i=0;i<5;i++)this.spark(f.x+Phaser.Math.Between(-55,55),f.y-Phaser.Math.Between(20,120));return}if(kind==='damo'){this.toast('DAMO GROUND SLAM — MOVE, CUNT',900);const mark=this.add.ellipse(this.player.x,640,380,38,0xff3311,.25).setStrokeStyle(4,0xffcc22,.9).setDepth(1);this.tweens.add({targets:mark,scaleX:.25,alpha:.8,duration:520,onComplete:()=>{const x=mark.x;mark.destroy();this.cameras.main.shake(300,.025);if(Math.abs(this.player.x-x)<210)this.hurt(f.damage*1.4,f.x)}});return}}
 shoot(f:Foe){const dir=Math.sign(this.player.x-f.x)||1,s=this.shots.create(f.x+dir*40,f.y-55,'prop3-2') as Shot;s.damage=f.damage*.75;s.setScale(.3).setVelocityX(dir*390).setDepth(6);this.time.delayedCall(2500,()=>s.destroy())}
 projectileHit(s:Shot){const damage=s.damage??9,x=s.x;s.destroy();this.hurt(damage,x)}enemyContact(f:Foe){if(this.time.now>this.nextPlayerHit&&Math.abs(f.body!.velocity.x)>300)this.hurt(f.damage,f.x)}
 hurt(amount:number,sourceX:number){if(this.invulnerable||this.time.now<this.nextPlayerHit||!this.player.active)return;this.nextPlayerHit=this.time.now+650;this.state.damageTaken+=amount;this.state.hp=Math.max(0,this.state.hp-amount);this.state.high=Math.max(0,this.state.high-15);this.state.combo=0;this.player.setTexture('jack3-2').setVelocity((this.player.x<sourceX?-1:1)*430,-220).setTintFill(0xff3355);this.cameras.main.shake(160,.014);this.audio.hurt();this.time.delayedCall(170,()=>this.player.active&&this.player.clearTint());if(this.state.hp<=0)this.die()}
 dash(){if(this.invulnerable||this.attacking)return;this.invulnerable=true;this.audio.dash();this.player.setAlpha(.55).setVelocityX((this.player.flipX?-1:1)*620);this.player.setTexture('jack3-1');this.time.delayedCall(280,()=>{this.invulnerable=false;this.player.setAlpha(1)})}
 usePacket(){if(this.state.packets<1){this.toast('NO BAGS LEFT, YOU ABSOLUTE SCAB',900);return}this.state.packets--;this.unlock('bag','BAG FOR LIFE');this.state.high=100;this.damageBuff=2;this.player.setTexture('jack3-3').setTint(0x33ffcc);if(this.state.upgrades.has('rat'))this.heal(10);if(this.packetTimer)this.packetTimer.remove(false);this.packetTimer=this.time.delayedCall(this.state.upgrades.has('rat')?9000:6000,()=>{this.damageBuff=1;this.state.high=30;this.player.clearTint()});this.audio.special();this.toast('FUCK YES. TEMPORARILY INVINCIBLE IN YOUR OWN MIND.',1300)}
 pigeon(){const cost=this.state.upgrades.has('pigeon')?30:50;if(this.state.high<cost){this.toast(`NEED ${cost} HIGH TO SUMMON THE BIRD`,800);return}this.state.high-=cost;this.unlock('pigeon','AIR SUPERIORITY');this.audio.special();this.toast('PIGEONHOLE AIR SUPPORT — SHIT FROM ABOVE',1000);const p=this.physics.add.sprite(this.player.x-520,250,'prop0-1').setScale(.55).setDepth(12).setVelocityX(980);p.play('pigeon-fly');this.foes.children.each((o,i)=>{const f=o as Foe;this.time.delayedCall(180+Number(i)*90,()=>f.active&&this.hitFoe(f,4,(f.x<this.player.x?-1:1)*450));return true});this.time.delayedCall(2300,()=>p.destroy())}
 makeItRain(){if(this.state.cash<50){this.toast('NEED $50 TO MAKE IT RAIN, BROKE CUNT',700);return}this.state.cash-=50;let charmed=0;for(let i=0;i<9;i++){const note=this.add.image(this.player.x+Phaser.Math.Between(-160,160),this.player.y-Phaser.Math.Between(90,240),'prop1-4').setScale(.12).setDepth(14).setAngle(Phaser.Math.Between(-40,40));this.tweens.add({targets:note,y:650,x:note.x+Phaser.Math.Between(-90,90),angle:note.angle+180,alpha:0,duration:900+Phaser.Math.Between(0,350),onComplete:()=>note.destroy()})}this.foes.children.each(o=>{const f=o as Foe;if(f.active&&!f.dead&&ENEMIES[f.kind].sprite.startsWith('woman')&&Math.abs(f.x-this.player.x)<430){charmed++;f.setVelocityX(0).setTint(0xffd229);f.nextAttack=this.time.now+2600;f.setTexture(`${ENEMIES[f.kind].sprite}-3`);this.time.delayedCall(800,()=>f.active&&f.clearTint())}return true});this.state.high=Math.min(100,this.state.high+10*charmed);this.state.score+=69*charmed;this.unlock('rain','MAKE IT RAIN');this.toast(charmed?`$50 WELL WASTED — ${charmed} BADDIES DISTRACTED`:'YOU THREW $50 AT AN EMPTY ROOM',850)}
 drop(x:number,y:number,boss=false){if(!boss&&Math.random()>.6)return;const options=boss?['packet','kebab','hammer']:['packet','drink','cash','bottle','kebab'],loot=Phaser.Math.RND.pick(options);const map:Record<string,string>={packet:'prop1-1',drink:'prop1-2',kebab:'prop1-3',cash:'prop1-4',hammer:'prop2-1',bottle:'prop2-2'};const p=this.loot.create(x,y-40,map[loot]) as Loot;p.loot=loot;p.setScale(.32).setBounce(.5).setVelocity(Phaser.Math.Between(-80,80),-260).setDepth(3)}
 collect(p:Loot){if(!p.active)return;const type=p.loot;p.destroy();this.audio.pickup();if(type==='packet')this.state.packets++;if(type==='drink'){this.state.high=Math.min(100,this.state.high+25);this.heal(5)}if(type==='kebab')this.heal(30);if(type==='cash'){this.state.cash+=this.state.upgrades.has('filthy')?100:50;this.state.score+=69}if(type==='hammer'||type==='bottle')this.equip(type);this.toast(type==='kebab'?'GARLIC ARMOUR RESTORED 30 MEAT':type==='cash'?'FILTHY MONEY ACQUIRED':type==='packet'?'MYSTERY BAG SECURED':type==='drink'?'69 ENERGY: HEART PALPITATIONS ONLINE':`${type.toUpperCase()} EQUIPPED`,750)}
 equip(type:string){this.state.weapon=type;this.state.weaponHits=type==='hammer'?8:4;if(this.weaponView)this.weaponView.destroy();this.weaponView=this.add.image(this.player.x,this.player.y,type==='hammer'?'prop2-1':'prop2-2').setScale(.2).setDepth(7)}breakWeapon(){this.state.weapon='';this.state.weaponHits=0;this.weaponView?.destroy();this.weaponView=undefined;this.toast('WEAPON FUCKED. USE YOUR HANDS.',600)}
 heal(n:number){this.state.hp=Math.min(this.state.maxHp,this.state.hp+n)}
 advanceWave(){this.transition=true;const s=STAGES[this.state.stage];if(this.state.wave<s.waves.length-1){this.state.wave++;this.toast(this.state.wave===2?'BOSS INCOMING — TRY NOT TO EMBARRASS YOURSELF':`WAVE ${this.state.wave+1}: MORE BAD DECISIONS`,1000);this.time.delayedCall(1000,()=>{this.transition=false;this.startWave()})}else{this.toast(s.clear,1700);this.time.delayedCall(1300,()=>this.stageClear())}}
  stageClear(){if(this.state.stage>=STAGES.length-1){this.finish();return}this.physics.pause();const choices=Phaser.Utils.Array.Shuffle(UPGRADES.filter(u=>!this.state.upgrades.has(u.id))).slice(0,3);this.game.events.emit('upgrade',{stage:this.state.stage,choices,score:this.state.score,choose:(id:string)=>{this.applyUpgrade(id);this.state.stage++;this.state.wave=0;this.state.hp=Math.min(this.state.maxHp,this.state.hp+30);this.clearWorld();this.physics.resume();this.loadStage()}})}
 applyUpgrade(id:string){this.state.upgrades.add(id);if(id==='double'){this.state.maxHp-=10;this.state.hp=Math.min(this.state.hp,this.state.maxHp)}}
 die(){this.running=false;this.paused=true;this.player.setActive(false);this.playerShadow.setVisible(false);this.highAura.setVisible(false);this.physics.pause();this.audio.hurt();this.toast('YOU DIED AS YOU LIVED: MAKING IT EVERYONE ELSE\'S PROBLEM',1600);this.time.delayedCall(1200,()=>this.game.events.emit('gameover',{score:this.state.score,stage:this.state.stage,kills:this.state.kills,damage:this.state.damageTaken,difficulty:DIFFICULTIES[this.difficultyKey].name,retry:()=>{this.scene.restart({auto:true})}}))}
 finish(){this.running=false;this.transition=true;this.physics.pause();this.unlock('sunrise','SUNRISE SURVIVOR');const best=Math.max(Number(localStorage.getItem('ts69-best')||0),this.state.score),seconds=Math.round((Date.now()-this.state.startedAt)/1000);localStorage.setItem('ts69-best',String(best));localStorage.setItem('ts69-finished','1');this.game.events.emit('ending',{score:this.state.score,cash:this.state.cash,best,kills:this.state.kills,damage:this.state.damageTaken,seconds,difficulty:DIFFICULTIES[this.difficultyKey].name,retry:()=>this.scene.restart({auto:true})})}
 clearWorld(){this.foes?.children.each(o=>{const f=o as Foe;f.bar?.destroy();f.barBg?.destroy();f.shadow?.destroy();return true});this.foes?.clear(true,true);this.loot?.clear(true,true);this.shots?.clear(true,true);this.activeBoss=undefined;this.weaponView?.destroy();this.weaponView=undefined}
 togglePause(){if(!this.player.active)return;this.paused=!this.paused;if(this.paused){this.physics.pause();this.game.events.emit('pause',{resume:()=>{this.paused=false;this.physics.resume();this.game.events.emit('closeModal');this.game.events.emit('resumed')}})}else{this.physics.resume();this.game.events.emit('closeModal');this.game.events.emit('resumed')}}
 setBody(s:Phaser.Physics.Arcade.Sprite){s.setBodySize(58,165).setOffset(99,82)}
 spawnHazard(){const stage=this.state.stage;if(stage===0){this.toast('HAZARD: BOTTLE SERVICE FROM ABOVE',650);for(let i=0;i<5;i++)this.time.delayedCall(i*120,()=>this.fallingHazard('prop2-2',8))}else if(stage===1){const x=Phaser.Math.Clamp(this.player.x+Phaser.Math.Between(-220,220),120,1380);this.toast('LIVE PUDDLE — MOVE YOUR ARSE',650);const mark=this.add.rectangle(x,642,280,20,0x12e8ff,.22).setStrokeStyle(3,0x7effff,.9).setDepth(1);this.tweens.add({targets:mark,alpha:.8,scaleX:.35,duration:720,onComplete:()=>{const fx=this.add.image(x,620,'prop3-2').setScale(.25).setDepth(12);mark.destroy();this.tweens.add({targets:fx,scale:1.5,alpha:0,duration:430,onComplete:()=>fx.destroy()});if(Math.abs(this.player.x-x)<165)this.hurt(11,x)}})}else if(stage===2){this.toast('THE HOUSE IS COLLECTING INTEREST',650);for(let i=0;i<4;i++){const s=this.shots.create(1450,430+i*55,'prop3-3') as Shot;s.damage=9;s.setScale(.28).setVelocityX(-340-i*30).setDepth(8);this.time.delayedCall(4300,()=>s.destroy())}}else{this.toast('HOT GREASE RAIN — DAWN IS DISGUSTING',650);for(let i=0;i<7;i++)this.time.delayedCall(i*90,()=>this.fallingHazard('prop3-3',10))}}
 fallingHazard(key:string,damage:number){const s=this.shots.create(Phaser.Math.Clamp(this.player.x+Phaser.Math.Between(-360,360),60,1440),-60,key) as Shot;s.damage=damage;s.setScale(key==='prop2-2'?.2:.27).setAngularVelocity(Phaser.Math.Between(-220,220)).setVelocityY(Phaser.Math.Between(80,170)).setDepth(8);(s.body as Phaser.Physics.Arcade.Body).setAllowGravity(true);this.time.delayedCall(3200,()=>s.destroy())}
 spark(x:number,y:number){const fx=this.add.image(x,y,'prop3-3').setScale(.12).setDepth(13);this.tweens.add({targets:fx,scale:.55,alpha:0,angle:90,duration:420,onComplete:()=>fx.destroy()})}
 floatText(x:number,y:number,label:string,color:string){const t=this.add.text(x,y,label,{fontFamily:'Black Ops One',fontSize:'22px',color,stroke:'#090509',strokeThickness:5}).setOrigin(.5).setDepth(20);this.tweens.add({targets:t,y:y-70,alpha:0,scale:1.25,duration:650,ease:'Cubic.easeOut',onComplete:()=>t.destroy()})}
 unlock(id:string,name:string){let saved:string[]=[];try{saved=JSON.parse(localStorage.getItem('ts69-achievements')||'[]')}catch{}if(saved.includes(id))return;saved.push(id);localStorage.setItem('ts69-achievements',JSON.stringify(saved));this.game.events.emit('achievement',{name})}
 unlockBaddie(kind:EnemyKey){let saved:string[]=[];try{saved=JSON.parse(localStorage.getItem('ts69-gallery')||'[]')}catch{}if(saved.includes(kind))return;saved.push(kind);localStorage.setItem('ts69-gallery',JSON.stringify(saved));this.game.events.emit('achievement',{name:`${ENEMIES[kind].name} — AFTER-DARK DOSSIER`})}
 impact(x:number,y:number){const fx=this.add.image(x,y,'prop3-1').setScale(.24).setDepth(15);this.tweens.add({targets:fx,scale:.6,alpha:0,angle:90,duration:180,onComplete:()=>fx.destroy()})}
 blood(x:number,y:number){for(let i=0;i<12;i++){const c=this.add.circle(x,y-50,Phaser.Math.Between(2,7),0xd80b45).setDepth(3);this.tweens.add({targets:c,x:x+Phaser.Math.Between(-100,100),y:y+Phaser.Math.Between(-80,110),alpha:0,duration:Phaser.Math.Between(350,650),onComplete:()=>c.destroy()})}}
 toast(text:string,duration=900){this.game.events.emit('toast',{text,duration})}
 emitHud(){this.game.events.emit('hud',{...this.state,stageData:STAGES[this.state.stage],boss:this.activeBoss?{name:ENEMIES[this.activeBoss.kind].name,hp:this.activeBoss.hp,max:this.activeBoss.maxHp}:null})}
 createAnimations(){const add=(key:string,frames:string[],rate:number)=>{if(!this.anims.exists(key))this.anims.create({key,frames:frames.map(k=>({key:k})),frameRate:rate,repeat:-1})};add('jack-idle',[1,2,3,4].map(i=>`jack0-${i}`),3);add('jack-run',[1,2,3,4].map(i=>`jack1-${i}`),9);for(let r=0;r<8;r++)add(`woman${r}-walk`,[1,2].map(i=>`woman${r}-${i}`),5);for(let r=0;r<4;r++)add(`man${r}-walk`,[1,2].map(i=>`man${r}-${i}`),5);add('pigeon-fly',[1,2,3,4].map(i=>`prop0-${i}`),10)}
}
