import Phaser from 'phaser';import '@fontsource/black-ops-one/latin-400.css';import '@fontsource/oswald/latin-400.css';import '@fontsource/oswald/latin-600.css';import '@fontsource/oswald/latin-700.css';import './style.css';import {GameScene} from './game/GameScene';import {FilthyAudio} from './game/audio';import {UPGRADES} from './game/data';
const q=<T extends HTMLElement>(s:string)=>document.querySelector(s) as T;const audio=new FilthyAudio();const scene=new GameScene(audio);
const game=new Phaser.Game({type:Phaser.AUTO,width:1280,height:720,parent:'game',backgroundColor:'#090509',pixelArt:false,antialias:true,scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},physics:{default:'arcade',arcade:{gravity:{x:0,y:1050},debug:false}},scene:[scene]});
const overlay=q('#overlay'),modal=q('#modal'),hud=q('#hud'),touch=q('#touch'),toast=q('#toast');let toastTimer=0;
let difficulty=localStorage.getItem('ts69-difficulty')||'cooked';scene.setDifficulty(difficulty);document.querySelectorAll<HTMLButtonElement>('[data-diff]').forEach(b=>{b.classList.toggle('active',b.dataset.diff===difficulty);b.onclick=()=>{difficulty=b.dataset.diff!;localStorage.setItem('ts69-difficulty',difficulty);scene.setDifficulty(difficulty);document.querySelectorAll('[data-diff]').forEach(x=>x.classList.toggle('active',(x as HTMLElement).dataset.diff===difficulty))}});
q('#best').textContent=localStorage.getItem('ts69-best')?`PERSONAL WORST: ${Number(localStorage.getItem('ts69-best')).toLocaleString()} POINTS`:'';
try{const n=JSON.parse(localStorage.getItem('ts69-achievements')||'[]').length;q('#best').textContent+=`${q('#best').textContent?' • ':''}${n}/8 DEGENERACIES UNLOCKED`}catch{}
q('#start').onclick=()=>{audio.start();document.body.classList.add('game-active');overlay.classList.add('gone');hud.classList.remove('gone');touch.classList.remove('gone');scene.startRun()};
q('#cast').onclick=()=>showCast();q('#mute').onclick=()=>{q('#mute').textContent=audio.toggle()?'×':'♪'};
function closeModal(){modal.classList.add('gone');modal.innerHTML=''}
function showCast(){let unlocked:string[]=[];try{unlocked=JSON.parse(localStorage.getItem('ts69-gallery')||'[]')}catch{}const cast=[['roxi','Roxi Redline','woman-row0','A five-alarm redhead with expensive taste and thighs that could cancel your insurance.'],['lexi','Lexi Platinum','woman-row1','VIP hostility poured into silver. Bottle service, zero emotional service.'],['nyx','Nyx Damage','woman-row2','Tattooed goth gravity well. You know she is a red flag; that is apparently the attraction.'],['candy','Candy Gold','woman-row3','Glitter, muscle and financial consequences. Tips accepted. Excuses rejected.'],['viper','Viper Vice','woman-row4','Emerald poison in thigh-high boots. Makes eye contact like a legally binding threat.'],['lola','Lola Leopard','woman-row5','Big hair, bigger curves, catastrophic decision-making radius.'],['suki','Suki Static','woman-row6','Rave voltage with enough bass to rearrange your organs and browsing history.'],['bianca','Bianca Blackout','woman-row7','White suit, black ledger. She owns the room and half your future income.']];modal.innerHTML=`<div class="age">AFTER-DARK BADDIE DOSSIERS • ${unlocked.length}/8 DROPPED</div><h2>THE PROBLEMS</h2><div class="cards after-dark">${cast.map(([key,n,row,d])=>`<article class="card ${unlocked.includes(key)?'unlocked':'locked'}"><img src="assets/characters/${row}/01.png"><h3>${n}</h3><p>${unlocked.includes(key)?d:'DROP HER IN-GAME TO UNLOCK THE FILTHY DOSSIER.'}</p></article>`).join('')}</div><button id="back">BACK TO THE BAD IDEA</button>`;modal.classList.remove('gone');q('#back').onclick=closeModal}
game.events.on('toast',({text,duration}:{text:string,duration:number})=>{toast.innerText=text;clearTimeout(toastTimer);toastTimer=window.setTimeout(()=>toast.innerText='',duration)});
let bossTimer=0;game.events.on('bossIntro',({name,line,image}:{name:string;line:string;image:string})=>{q<HTMLImageElement>('#boss-portrait').src=image;q('#boss-card-name').textContent=name;q('#boss-card-line').textContent=line;const card=q('#boss-card');card.classList.remove('gone');clearTimeout(bossTimer);bossTimer=window.setTimeout(()=>card.classList.add('gone'),2300)});
let achievementTimer=0;game.events.on('achievement',({name}:{name:string})=>{q('#achievement-name').textContent=name;const a=q('#achievement');a.classList.remove('gone');clearTimeout(achievementTimer);achievementTimer=window.setTimeout(()=>a.classList.add('gone'),2400)});
game.events.on('hud',(s:any)=>{q('#hp-text').textContent=String(Math.ceil(s.hp));q<HTMLElement>('#hp-bar').style.width=`${Math.max(0,s.hp/s.maxHp*100)}%`;q('#high').textContent=String(Math.floor(s.high));q<HTMLElement>('#high-bar').style.width=`${Math.max(0,s.high)}%`;q('#packets').textContent=String(s.packets);q('#cash').textContent=String(s.cash);q('#weapon').textContent=s.weapon?s.weapon.toUpperCase():'FISTS';q('#score').textContent=s.score.toLocaleString();q('#act').textContent=s.stageData.act;q('#venue').textContent=s.stageData.name;q('#wave').textContent=`WAVE ${s.wave+1}/3`;const combo=q('#combo');combo.innerHTML=`${s.combo}× <small>${s.combo>8?'ABSOLUTE FILTH':s.combo>4?'DISGUSTING':'FILTHY'}</small>`;combo.classList.toggle('gone',s.combo<2);const bw=q('#boss-wrap');bw.classList.toggle('gone',!s.boss);if(s.boss){q('#boss-name').textContent=s.boss.name;q<HTMLElement>('#boss-bar').style.width=`${Math.max(0,s.boss.hp/s.boss.max*100)}%`}});
game.events.on('upgrade',({choices,choose}:any)=>{modal.innerHTML=`<div class="age">ACT SURVIVED • CHOOSE YOUR NEXT DISORDER</div><h2>DEGENERATE UPGRADE</h2><div class="choices">${choices.map((u:(typeof UPGRADES)[number])=>`<button class="choice" data-id="${u.id}"><b>${u.name}</b><small>${u.desc}</small></button>`).join('')}</div>`;modal.classList.remove('gone');modal.querySelectorAll<HTMLButtonElement>('[data-id]').forEach(b=>b.onclick=()=>{closeModal();choose(b.dataset.id)})});
game.events.on('pause',({resume}:any)=>{audio.pause(true);modal.innerHTML=`<div class="age">COWARD'S INTERMISSION</div><h2>PAUSED</h2><p>Hydrate. Lie to yourself. Continue.</p><button id="resume">GET BACK IN THERE</button>`;modal.classList.remove('gone');q('#resume').onclick=()=>{closeModal();resume()}});game.events.on('resumed',()=>audio.pause(false));game.events.on('closeModal',closeModal);
game.events.on('gameover',({score,stage,kills,damage,difficulty,retry}:any)=>{audio.pause(true);hud.classList.add('gone');touch.classList.add('gone');modal.innerHTML=`<div class="age">RUN TERMINATED • ${difficulty}</div><h2>ABSOLUTELY FUCKED IT</h2><p>You reached ${stage+1}/4 venues and scraped together <b>${score.toLocaleString()}</b> points.</p><p class="stats">BADDIES DROPPED ${kills}　•　MEAT LOST ${Math.round(damage)}</p><div class="menu-actions"><button id="retry">MAKE THE SAME MISTAKES AGAIN</button><button id="title" class="secondary">TITLE + DOSSIERS</button></div>`;modal.classList.remove('gone');q('#retry').onclick=()=>{audio.pause(false);document.body.classList.add('game-active');closeModal();hud.classList.remove('gone');touch.classList.remove('gone');retry()};q('#title').onclick=()=>location.reload()});
game.events.on('ending',({score,cash,best,kills,damage,seconds,difficulty,retry}:any)=>{audio.pause(true);hud.classList.add('gone');touch.classList.add('gone');const time=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;modal.innerHTML=`<div class="age">DAWN ENDING UNLOCKED • ${difficulty}</div><h1>STILL<br><span>UNCAGED</span></h1><h2>YOU SURVIVED, CUNT.</h2><p>The sun rose. Damo fell. The kebab was medicinal.<br>You remember roughly 14% of the evening.</p><p class="stats">SCORE ${score.toLocaleString()}　•　CASH $${cash}　•　BEST ${best.toLocaleString()}<br>BADDIES ${kills}　•　MEAT LOST ${Math.round(damage)}　•　TIME ${time}</p><div class="menu-actions"><button id="retry">RUIN ANOTHER NIGHT</button><button id="title" class="secondary">VIEW UNLOCKED BADDIES</button></div>`;modal.classList.remove('gone');q('#retry').onclick=()=>{audio.pause(false);document.body.classList.add('game-active');closeModal();hud.classList.remove('gone');touch.classList.remove('gone');retry()};q('#title').onclick=()=>location.reload()});
if('serviceWorker' in navigator&&import.meta.env.PROD)navigator.serviceWorker.register('/sw.js').catch(()=>{});
document.querySelectorAll<HTMLButtonElement>('#touch [data-action]').forEach(b=>{const a=b.dataset.action!;b.addEventListener('pointerdown',e=>{e.preventDefault();game.events.emit('touch',a,true)});for(const ev of ['pointerup','pointercancel','pointerleave'])b.addEventListener(ev,()=>game.events.emit('touch',a,false))});
window.addEventListener('blur',()=>game.events.emit('autopause'));
